AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ondo-choseikun

  温度調整くん。

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs10.x
    Environment:
      Variables:
        NODE_ENV: local

Resources:
  GraphQLFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: index.graphQLHandler
      Events:
        GetGraphQL:
          Type: Api
          Properties:
            Path: /graphql
            Method: get
        PostGraphQL:
          Type: Api
          Properties:
            Path: /graphql
            Method: post
