AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  ondo-choseikun

  温度調整くん。

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs10.x

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/dist/
      Handler: index.helloHandler
      Events:
        Hello:
          Type: Api
          Properties:
            Path: /hello
            Method: get
